name: Build and deploy .NET Core app to Windows WebApp coreapisnew
on:
  push:
    branches:
    - master
env:
  AZURE_WEBAPP_NAME: coreapisnew
  AZURE_WEBAPP_PACKAGE_PATH: CoreAPIs/publish
  AZURE_WEBAPP_PUBLISH_PROFILE: ${{ secrets.coreapisnew_caa0 }}
  CONFIGURATION: Release
  DOTNET_CORE_VERSION: 5.0.x
  WORKING_DIRECTORY: CoreAPIs
jobs:
  build-and-deploy:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_CORE_VERSION }}
    - name: Restore
      run: dotnet restore "${{ env.WORKING_DIRECTORY }}"
    - name: Build
      run: dotnet build "${{ env.WORKING_DIRECTORY }}" --configuration ${{ env.CONFIGURATION }} --no-restore
    - name: Test
      run: dotnet test "${{ env.WORKING_DIRECTORY }}" --no-build
    - name: Trigger GitHub pages rebuild
      run: |
        curl --location --request POST 'https://www.apimatic.io/api/portal' --header 'Authorization: X-Auth-Key uTmxzngzCkKBvmtmr_LcXbuUQsAOYAmhvCkKyZqyRcTGv2lmHwNXcX-6RuAOvuus' --form 'file=@"${{ env.WORKING_DIRECTORY }}/APIMatic.zip"' -o  "${{ env.WORKING_DIRECTORY }}/StorePortal.zip"
    - name: Decompress Portal.zip
      run: 7z x "${{ env.WORKING_DIRECTORY }}/StorePortal.zip" -o"${{ env.WORKING_DIRECTORY }}/StorePortal"
    - name: Azure Static Web Apps Deploy
        id: deploytoazure
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: "c2e7eaafd1b8893a34f6a23ad012429584a0abaae7e6e142823d7f835b6df8840-e4707354-0138-4f2d-8d55-1f678ff5057001038703"
          ###repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations ######
          app_location: "${{ env.WORKING_DIRECTORY }}/StorePortal" # App source code path
          ###api_location: "api" # Api source code path - optional
          output_location: "public" # Built app content directory - optional
          ###### End of Repository/Build Configurations ######
    - name: Publish
      run: dotnet publish "${{ env.WORKING_DIRECTORY }}" --configuration ${{ env.CONFIGURATION }} --no-build --output "${{ env.AZURE_WEBAPP_PACKAGE_PATH }}"
    - name: Deploy to Azure WebApp
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
        publish-profile: ${{ env.AZURE_WEBAPP_PUBLISH_PROFILE }}
    - name: Publish Artifacts
      uses: actions/upload-artifact@v1.0.0
      with:
        name: webapp
        path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
